# Sonata Notification Bundle
# Configuration: https://sonata-project.org/bundles/notification/master/doc/reference/advanced_configuration.html
sonata_notification:
#    class:
#        message: App\Application\Sonata\NotificationBundle\Entity\Message

    backend: sonata.notification.backend.runtime
