# Sonata Notification Bundle
# Configuration: https://sonata-project.org/bundles/notification/master/doc/reference/advanced_configuration.html
sonata_notification:
    class:
        message: App\Application\Sonata\NotificationBundle\Entity\Message

    admin:
        enabled: true

    backend: sonata.notification.backend.doctrine

    backends:
            doctrine:
                message_manager:      sonata.notification.manager.message.default

                # The max age in seconds
                max_age:              86400

                # The delay in microseconds
                pause:                500000

                # The number of items on each iteration
                batch_size:           10

                # Raising errors level
                states:
                    in_progress:          10
                    error:                20
                    open:                 100
                    done:                 10000
