# Sonata Payment Bundle
sonata_payment:
    services:
        pass:
            name:    Pass
#            enabled: true
            code:    pass
            browser: sonata.payment.browser.curl

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                shop_secret_key: some-secret-key
                url_callback:    sonata_payment_callback
                url_return_ko:   sonata_payment_error
                url_return_ok:   sonata_payment_confirmation

    # service which find the correct payment methods for a basket
    selector: sonata.payment.selector.simple

    # service which generate the correct order and invoice number
    generator: sonata.payment.generator.mysql # or sonata.payment.generator.postgres

    transformers:
        order:  sonata.payment.transformer.order
        basket: sonata.payment.transformer.basket
