# Sonata SEO Bundle
# Configuration: https://sonata-project.org/bundles/seo/2-x/doc/reference/installation.html
sonata_seo:
    encoding:         UTF-8
    page:
        title:            Sandbox Sonata Commerce Symfony 3
        default:          sonata.seo.page.default
        metas:
#            name:
#                keywords:             foo bar
#                description:          The description
#                robots:               index, follow

            property:
                # Facebook application settings
#                'fb:app_id':          XXXXXX
#                'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Sandbox Sonata Commerce Symfony 3
                'og:description':     A sandbox of Sonata Commerce Bundle with Symfony 3.

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
#                'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
#            'xmlns:fb':           "http://www.facebook.com/2008/fbml"
